version: "3"

services:
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak
    tty: true
    stdin_open: true
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: passwd
    ports:
      - 18080:8080
    volumes:
      - ./data/keycloak:/opt/keycloak/data
    command:
      - "start-dev"